name: rich_text_editor_example
description: Example app for rich_text_editor package.
publish_to: "none"
version: 0.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rich_text_editor:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
